Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [7]:
!pip install numpy

In [4]:
import numpy as np

##create array  using numpy
##Create a 10 array
arr1 =np.array([1,2,3,4,5,6,7,8,9])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(9,)


In [ ]:
#1D ARRAY
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) #1 row and 5 column

array([[1, 2, 3, 4, 5]])

In [16]:
arr2 = np.array([
    [1,2,3,4,5]
    ])
arr2.shape

(1, 5)

In [ ]:
#2D ARRAY

arr2 =np.array([
                [1,2,3,4,5],
                [1,2,3,4,5]
                ])
print(arr2.shape)
print(arr2)

(2, 5)
[[1 2 3 4 5]
 [1 2 3 4 5]]
