Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [22]:
!pip install numpy

In [9]:
import numpy as np

##create array  using numpy
##Create a 10 array
arr1 =np.array([1,2,3,4,5,6,7,8,9])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(9,)


In [24]:
#1D ARRAY
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) #1 row and 5 column

array([[1, 2, 3, 4, 5]])

In [25]:
arr2 = np.array([
    [1,2,3,4,5]
    ])
arr2.shape

(1, 5)

In [ ]:
#2D ARRAY

arr2 =np.array([
                [1,2,3,4,5],
                [1,2,3,4,5]
                ])
print(arr2.shape)
print(arr2)

(2, 5)
[[1 2 3 4 5]
 [1 2 3 4 5]]


In [31]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [33]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#attribute of numpy
arr = np.array([
    [1,2,3,4],
    [5,6,7,8]
    ])

print("array:\n", arr)
print("shape:", arr.shape)
print("number of dimension:", arr.ndim)
print("size(number of elemnt):", arr.size)
print("data type", arr.dtype)
print("item size (in bytes):", arr.itemsize)

array:
 [[1 2 3 4]
 [5 6 7 8]]
shape: (2, 4)
number of dimension: 2
size(number of elemnt): 8
data type int32
item size (in bytes): 4


In [46]:
##numpy of vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#Element wise addition
print("addition:", arr1+arr2)

#Element wise substraction
print("substraction:", arr1-arr2)

#Element wise multiplication
print("multiple:", arr1*arr2)

#Element wise divided
print("divided:", arr1/arr2)

addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]
multiple: [ 10  40  90 160 250]
divided: [0.1 0.1 0.1 0.1 0.1]


In [16]:
##Universal Function
arr3 = np.array([6,8,10])

##square root
print(np.sqrt(arr3))

##Exponential
print(np.exp(arr3))

##sine
print(np.sin(arr3))

#natural log
print(np.log(arr3))


[2.44948974 2.82842712 3.16227766]
[  403.42879349  2980.95798704 22026.46579481]
[-0.2794155   0.98935825 -0.54402111]
[1.79175947 2.07944154 2.30258509]


In [40]:
##array slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])

print("array: \n", arr)

print(arr[1][2])

print(arr[1:])

print(arr[1:,2:])

print(arr[0:2,2:])



array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]


In [ ]:
##Modify the element
arr[0,0] = 100

arr[0,3]= 150

arr[1,2] = 200
print(arr)

[[100   2   3 150]
 [  5   6   7   8]
 [  9  10  11  12]]


In [43]:
##Statistical concept -- normalization
## To have a mean of 0 and standard Deviation of 1

data = np.array([1,2,3,4,5,6])

## Calculate the Mean and Standard Deviation
mean = np.mean(data)
print(mean)

std_dev = np.std(data)
print(std_dev)

## Normalization The Data 
normalized_data = (data -mean) / std_dev

print("normalization data: ", normalized_data)


3.5
1.707825127659933
normalization data:  [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


In [45]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean 
mean = np.mean(data)
print("mean:", mean)

#median
median = np.median(data)
print("meadian:", median)

#standard devication
std = np.std(data)
print("standar devication: ", std)

#variance 
variance = np.var(data)
print("varibale :", variance )



mean: 5.5
meadian: 5.5
standar devication:  2.8722813232690143
varibale : 8.25
